### ISSUE TITLE
荣耀x40，华为nova 9se，vivo 53s这些机型无法扫码，没反应

### ISSUE THREAD

**Issue by geeklx** [ITxiaoguang/MLKitScanner#3]
求助：荣耀x40，华为nova 9se，vivo 53s这些机型无法扫码，没反应

**Comment by ITxiaoguang** [comment]
没有这些机型呢
更新这些版本
implementation "androidx.camera:camera-core:${camerax_version}"
implementation "androidx.camera:camera-camera2:${camerax_version}"
implementation "androidx.camera:camera-lifecycle:${camerax_version}"
implementation "androidx.camera:camera-view:1.0.0-alpha25"
当然，更新的话，改动代码比较大
试试这个呢 https://github.com/jenly1314/MLKit

**Comment by geeklx** [comment]
> 没有这些机型呢 更新这些版本 implementation "androidx.camera:camera-core:${camerax_version}" implementation "androidx.camera:camera-camera2:${camerax_version}" implementation "androidx.camera:camera-lifecycle:${camerax_version}" implementation "androidx.camera:camera-view:1.0.0-alpha25" 当然，更新的话，改动代码比较大 试试这个呢 https://github.com/jenly1314/MLKit

我改好了，谢谢大佬~
