### ISSUE TITLE
在OPPO手机上，无法识别到二维码或条形码

### ISSUE THREAD

**Issue by superoidlau** [ITxiaoguang/MLKitScanner#4]
在华为、小米上可以识别到，但是在OPPO上识别不到，使用[MLKit]( https://github.com/jenly1314/MLKit.git)是可以的。

**Comment by ITxiaoguang** [comment]
嗯嗯，先用MLKit呗。我这个就是多了一层面板，可以参考学习。扫码核心已经落后很多个版本了。

**Comment by superoidlau** [comment]
> 

好的。
